<?xml version="1.0" encoding="utf-8"?><Database Name="Stocks" Class="StocksDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MERSEY-PC;Initial Catalog=Stocks;Persist Security Info=True;User ID=sa" SettingsObjectName="Investment.Framework.Properties.Settings" SettingsPropertyName="StocksConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbStockShare" Member="tbStockShare">
    <Type Name="tbStockShare">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="日期" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="证券代码" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="证券名称" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="证券数量" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="可卖数量" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="成本价" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="当前价" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="最新市值" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="累计浮动盈亏" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="盈亏比例" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="股东代码" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbStockExchangeList" Member="tbStockExchangeList">
    <Type Name="tbStockExchangeList">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="成交日期" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="业务名称" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="证券代码" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="证券名称" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="成交价格" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="成交数量" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="剩余数量" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="成交金额" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="清算金额" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="剩余金额" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="净佣金" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="规费" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="印花税" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="过户费" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="结算费" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="附加费" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="成交编号" Type="System.String" DbType="NVarChar(24) NOT NULL" CanBeNull="false" />
      <Column Name="股东代码" Type="System.String" DbType="NVarChar(24) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbStockIndexPrice" Member="tbStockIndexPrice">
    <Type Name="tbStockIndexPrice">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="证券代码" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="日期" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="证券名称" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="开盘价格" Type="System.Decimal" DbType="Decimal(12,4) NOT NULL" CanBeNull="false" />
      <Column Name="最高价格" Type="System.Decimal" DbType="Decimal(12,4) NOT NULL" CanBeNull="false" />
      <Column Name="最低价格" Type="System.Decimal" DbType="Decimal(12,4) NOT NULL" CanBeNull="false" />
      <Column Name="收盘价格" Type="System.Decimal" DbType="Decimal(12,4) NOT NULL" CanBeNull="false" />
      <Column Name="指数类型" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="交易日类型" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbStockOptionSummary" Member="tbStockOptionSummary">
    <Type Name="tbStockOptionSummary">
      <Column Name="recordtime" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="资产" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="浮动盈亏" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="可用资金" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="风险度" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="上证指数" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
      <Column Name="上证50ETF" Type="System.Decimal" DbType="Decimal(8,3) NOT NULL" CanBeNull="false" />
      <Column Name="年化收益率" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="DateType" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="本金" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbStockPrice" Member="tbStockPrice">
    <Type Name="tbStockPrice">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="证券代码" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="日期" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="证券名称" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="开盘价格" Type="System.Decimal" DbType="Decimal(12,4) NOT NULL" CanBeNull="false" />
      <Column Name="最高价格" Type="System.Decimal" DbType="Decimal(12,4) NOT NULL" CanBeNull="false" />
      <Column Name="最低价格" Type="System.Decimal" DbType="Decimal(12,4) NOT NULL" CanBeNull="false" />
      <Column Name="收盘价格" Type="System.Decimal" DbType="Decimal(12,4) NOT NULL" CanBeNull="false" />
      <Column Name="类型" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbConfig" Member="tbConfig">
    <Type Name="tbConfig">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbStockProfit" Member="tbStockProfit">
    <Type Name="tbStockProfit">
      <Column Name="日期" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="盈亏" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="证券市值" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.Proc_GetStockFirstDealDay" Method="Proc_GetStockFirstDealDay">
    <Parameter Name="Time" Parameter="time" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="Proc_GetStockFirstDealDayResult">
      <Column Name="证券代码" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="证券名称" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="成交日期" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="类型" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="c" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>